require "uifaces/version"

module UIFaces
  def self.face(index = nil)
    index ||= rand(0..UIFACES.size - 1)
    index = index % UIFACES.size
    "https://s3.amazonaws.com/uifaces/faces/twitter/#{UIFACES[index]}/128.jpg"
  end

  UIFACES = %w(
    acoops_
    adellecharles
    adn
    akifyaldir
    alagoon
    alek_djuric
    Alvaro_Nistal
    andrewpautler
    AngelZxxWingZ
    Anotherdagou
    antoniopratas
    ariona_rian
    arjunchetna
    axelbouaziz
    beastydesign
    benefritz
    benhowdle
    benpeck
    BillSKenney
    blakesimkins
    bradenhamm
    brad_frost
    brampitoyo
    calebogden
    calvintennant
    cameronmoll
    cibawoman
    ckor
    CrafterSama
    damenleeturks
    danbenoni
    danielhaim
    daniel_love
    dannpetty
    daryl
    dbox
    decarola
    deimler
    desaiguddu
    designer_dean
    Djeje
    dvidsilva
    eldelentes
    eomerx
    fabioChannel
    feliperibeiros
    Fitehal
    FreelanceNathan
    Fubaruba
    gabediaz
    garrettgee
    gerrenlamson
    gerwitz
    gilbertglee
    haibnu
    horaciosoares
    hvillega
    iamjamie
    iamlouisbullock
    imfine_thankyou
    itolmach
    jackalstudio
    jacobseethaler
    jadlimcaco
    jayman
    jayrobinson
    jcarlosweb
    JeffChausse
    jina
    jjmpsp
    jodyferry
    jonsuh
    jpadilla_
    jsngr
    JuliaYunLiu
    jwphillips
    kirkouimet
    kolage
    kristijantaken
    leevigraham
    luhman
    macvhustle
    madysondesigns
    mambows
    MarkusOkur
    matejsudar
    max9xs
    mcmieras
    mds
    meddeg
    mijustin
    mikebeecham
    mist3r_c0r3
    mkalalang
    molovo
    motherfuton
    myusuf3
    NastyaVZ
    nckjrvs
    nettatheninja
    neweravin
    nick_persad
    nimaa
    nzcode
    odaymashalla
    ogvidius
    OskarLevinson
    owlfurty
    pixeliris
    pizzulata
    polovecn
    PtiteNoli
    Rafa3mil
    redkeg
    renbyrd
    ripplemdk
    rizwaniqbal
    rogie
    roybarberuk
    russellsmith21
    ryanAmurphy
    ryanleroux
    ryanlfoster
    sajtoo
    sauro
    ShaunMoynihan
    smharley
    steno
    stephane
    stylecampaign
    syswarren
    teleject
    temonehm
    th3ya0vi
    ThisIsJohnBrown
    tiagocamargo
    timothycd
    todd_coleman
    tonychester
    toodlenoodle
    utroda
    uxceo
    vctrfrnndz
    vehbikilic
    VinThomas
    walterstephanie
    waqar_alamgir
    WhatTheFerguson
    wrightmartin
    zulsdesign
    _joshnh
  )
end
